version: '2'

services:
  app:
    image: 'outages-api:v1.0'
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - CONTROL_DATE=2022-01-01T00:00:00.000Z
      - DO_INTEGRATION_TESTS=false
      - BASE_URL=https://api.krakenflex.systems/interview-tests-mock-api/v1/
      - API_KEY=EltgJ5G8m44IzwE6UN2Y4B4NjPW77Zk6FJK3lL23